var apps = [
  {appid:'lampa',name:'Lampa',url:'http://lampa.mx/',text:'Новое полностью бесплатное приложение для Smart TV'},
  {appid:'vokino',name:'vokino',url:'http://web.vokino.pro/',text:'Смотреть зарубежные фильмы и сериалы в хорошем качестве'},
  {appid:'atodo',name:'Atodo',url:'http://msx.benzac.de/?start=menu:request:interaction:menu@http://atodo.fun/fun.html',text:'АТОDO'},
  {appid:'fxml',name:'Media Station X',url:'http://msx.benzac.de/foxxum.html',text:'Приложение для создания настраиваемых мультимедийных страниц (видео, аудио и пр.)'},
  {appid:'moovies',name:'Moovies',url:'http://msx.benzac.de/?start=menu:request:interaction:init@http://moovies.uz/index.html',text:'Moovies for MSX'},
  {appid:'movielab',name:'Movielab',url:'https://msx.benzac.de/?start=menu:https://movielab.fun/msx/menu.json',text:'Наслаждайтесь просмотром лучших фильмов с MovieLab'},
  {appid:'deeplex',name:'DEEPLEX',url:'http://smart.deeplex.cc',text:'Фильмы, сериалы и многое другое без ограничений. Инструкция -> http://deeplex.cc/#/instructions'},
  {appid:'drmplay',name:'DRM-play',url:'http://drm-play.com',text:'Ott-плеер drm-play, mod-плеера ott-play by Alex'},
  // {appid:'msx',name:'MSXPlayer',url:'http://msx.benzac.de/?welcome=menu:request:interaction:menu@http://plugins.msxplayer.ru/store.html',text:'Лаунчер приложений, TorrServer-клиент, FXML-браузер, IPTV-просмотр…'},
  {appid:'fork',name:'ForkPlayer',url:'http://browser.appfxml.com/',text:'ForkPlayer — это браузер с адаптированным под ваше устройство просмотром сайтов'},
  {appid:'forkbrowser',name:'Fork Browser',url:'http://browser.appinfo.su/',text:'Новая, улучшенная версия ForkPlayer'},
  {appid:'lampalite4',name:'Lampa lite',url:'http://lite.lampa.mx/',text:'Lampa Lite, облегчённая версия приложения для онлайн просмотра.'},
  {appid:'twitch',name:'twitch',url:'https://ryxjogfhxnvjuptmzkhk.tv.twitch.tv',text:'Видеостриминговый сервис, специализирующийся на тематике компьютерных игр.'},
  {appid:'vkvideo',name:'VK видео',url:'https://vk.ru/tv-app/lib?version=latest&platform=vidaa',text:'Смотрите видеозаписи ВКонтакте на большом экране SmartTV.'},

  {appid:'beeline',name:'Билайн ТВ',url:'https://smart-vidaa.beeline.tv/',text:'Тысячи фильмов, сериалов и мультфильмов. 300 каналов и доступ к онлайн-кинотеатру beeline.tv.'},
  {appid:'xsmart',name:'Xsmart',url:'http://app.xsmart.tv/?widg=5',text:'Приложение для Smart TV, которое объединяет в себе различные функции.'},
  // {appid:'xsmartlite',name:'Xsmart classic',url:'http://app.xsmart.tv/?widg=lite',text:'Приложение для Smart TV, которое объединяет в себе различные функции. Lite версия приложения.'},
  {appid:'viju',name:'Viju',url:'https://smarttv.viju.ru',text:'Viju – это лучшие фильмы, сериалы и мультфильмы по подписке'},
  // {appid:'lava',name:'LAVA',url:'https://html5.lavaonline.tv',text:'Площадка для бесплатного просмотра современного российского кино'},
  // {appid:'tiktok',name:'TikTok',url:'https://tv.tiktok.com/webos',text:'Ведущая видеоплатформа для коротких видео'},
  {appid:'flex',name:'FLEX',url:'https://tv.back-films.ru',text:'Онлайн-кинотеатр с фильмами и сериалами в отличном качестве и профессиональном озвучивании!'},
  {appid:'m3uiptv',name:'M3U IPTV',url:'https://m3u-ip.tv/lg/',text:'Просто загрузите свой плейлист IPTV по URL-адресу (в виде файла m3u или m3u8) и вперёд'},
  {appid:'kinopoisk',name:'Кинопоиск',url:'https://smarttv-app.ott.yandex.ru/?ott-rv=vidaa',text:'Крупнейший русскоязычный онлайн-кинотеатр.'},
  {appid:'yandexvideo',name:'Яндекс видео',url:'https://yandex.ru/video/tvapp/?ui=tvapp',text:'Смотреть телепередачи, музыкальные клипы, игровые ролики и популярное на YouTube'},
  {appid:'ott',name:'OttPlayer',url:'http://widget.ottplayer.tv/operatv2/index.html',text:'Сервис, который позволяет вам собрать всё ваше IP-телевидение в одном плейлисте.'},
  {appid:'ottold',name:'OttPlayerTest',url:'http://widget.ottplayer.tv/test/index.html',text:'OttPlayer, более новая (тестовая версия приложения)'},
  {appid:'wink',name:'Wink',url:'https://production-vidaa-fhd.wink.ru/',text:'Цифровой видеосервис компании «Ростелеком»'},
  {appid:'kion',name:'Кион',url:'http://hkion.kion.ru/',text:'Российская мультимедийная онлайн-платформа, созданная компанией МТС'},
  {appid:'ssiptv',name:'ssiptv',url:'http://app.ss-iptv.com',text:'Медиа сервер для просмотра фильмов, сериалов, мультфильмов и пр.'},
  {appid:'icva',name:'ICVA',url:'http://icva.mx/',text:'ICVA - новое приложение для просмотра IPTV каналов'},

  {appid:'tvap',name:'TVap',url:'http://tvphone.site/',text:'TVap - просмотр IPTV каналов на Smart TV'},
  {appid:'peers',name:'PeersTV',url:'http://smarttv.peers.tv/hisense/hisense-1.0.0/',text:'Бесплатное приложение для просмотра ТВ онлайн и в записи. Лайт версия без рекламы'},
  {appid:'bonus',name:'Бонус ТВ',url:'http://app.bonus-tv.ru/lg/',text:'Телевидение онлайн на смартфоне, планшете, Smart-телевизоре или ТВ-приставке.'},
  {appid:'amediateka',name:'Амедиатека',url:'https://smarttv.amediateka.tech/v2/vidaa/',text:'Онлайн-сервис Амедиатека и телеканалы AMEDIA TV. Лучшие сериалы планеты'},
  // {appid:'forkbrowser',name:'Fork Browser',url:'http://browser.appinfo.su/',text:'Новая, улучшенная версия ForkPlayer'},
  {appid:'prisma',name:'Prisma',url:'http://prisma.ws/',text:'Полностью готовый к работе форк Lampa.'},
  // {appid:'ott',name:'OttPlayer',url:'http://widget.ottplayer.tv/operatv2/index.html',text:'Сервис, который позволяет вам собрать всё ваше IP-телевидение в одном плейлисте.'},
  // {appid:'ottold',name:'OttPlayerTest',url:'http://widget.ottplayer.tv/test/index.html',text:'OttPlayer, более новая (тестовая версия приложения)'},
  {appid:'gets',name:'GetsTV',url:'https://getstv.com/app/',text:'Приложение для просмотра ТВ, фильмов и сериалов.'},
  {appid:'ottplay_mod',name:'OTT-Play FOSS',url:'http://ott.prog4food.eu.org/f/',text:'Мод iptv-плеера Ott-Play by Alex. Отсутствие баннеров и блокировки каналов.'},
  {appid:'kinopub',name:'KinoPubTV',url:'http://cdnservices.link',text:'Неофициальный клиент для популярного онлайн-кинотеатра'},
  // {appid:'kinopub2',name:'KinoPubTV',url:'https://kpms.cc',text:'Неофициальный клиент для популярного онлайн-кинотеатра.'},
  // {appid:'kinopub2',name:'KinoPub',url:'http://kpstv.net/app/hisense/',text:'Ещё один неофициальный клиент для онлайн-кинотеатра kinopub'},
  {appid:'lampaun',name:'ByLampa',url:'http://bylampa.online/',text:'Неофициальный форк онлайн-кинотеатра Lampa'},
  {appid:'lampaland',name:'Lampa.land',url:'http://lampa.land',text:'Проект, созданный для тех, кто не может самостоятельно настроить приложение Lampa'},
  {appid:'iptvportal',name:'IPTVPORTAL',url:'http://go.iptvportal.ru/?screen=1280x720&user-agent=lg',text:'Просмотр IPTV из сетей провайдеров, подключённых к платформе IPTVPORTAL'},
  {appid:'oneplayer',name:'Oneplayer',url:'http://webos.oneplayer.me/',text:'Интернет-плеер с широким функционалом'},
  {appid:'clouddy',name:'ClouDDy',url:'http://player.clouddy.online/',text:'Продвинутый и удобный медиаплеер для воспроизведения вашего любимого медиаконтента.'},

  {appid:'smotreshka',name:'Смотрешка',url:'https://smotreshka.webapp.lfstrm.tv/loaders/vidaa/index.html',text:'Современное интерактивное телевидение'},
  // {appid:'ivikids',name:'IVI детям',url:'http://lgkids.ivi.ru',text:'Приложение, сделанное специально для детей! Мультфильмы, фильмы и сериалы'},
  {appid:'viloud',name:'Viloud',url:'https://app.viloud.tv//smarttv//v2//?associate=fox-a5f1&app=ef2b1dd758eb0fcc065561e1275e4af6#viloud',text:'Самая Простая и Доступная Онлайн-Видеоплатформа'},
  {appid:'vevo',name:'Vevo',url:'https://hisense.vevo.com',text:'Музыкальное видео от крупнейших звукозаписывающих корпораций'},
  {appid:'webvideocast2',name:'Web Video Cast',url:'http://vewd.webvideocaster.com/',text:'Позволяет вам транслировать любое видео, найденное на веб-сайтах, на ваш телевизор.'},
  {appid:'sweet',name:'sweet.tv',url:'http://foxxum240.sweet.tv',text:'Бесплатное онлайн телевидение в хорошем качестве. Телеканалы в прямом эфире и в записи!'},
  {appid:'stranafm',name:'Страна FM',url:'http://stranafm.bonus-tv.ru/stranafm/nettv/',text:'Страна FM — российский коммерческий развлекательный телеканал. Музыка нон стоп'},
  {appid:'premier',name:'PREMIER',url:'https://hisensesmarttv.premier.one/hisense/#/main',text:'ТНТ премьер. Новые русские сериалы, фильмы и шоу.'},
  {appid:'mytuner',name:'myTuner Radio',url:'https://devices.mytuner.mobi/?utm_source=Foxxum',text:'Удобное прослушивание более 30 000 популярных радиостанций 120 стран мира'},
  {appid:'zaycev',name:'Zaycev FM',url:'https://tv.zaycev.fm/index.html',text:'Любимая музыка теперь всегда будет с вами вместе с онлайн радио Zaycev.fm!'},
  {appid:'ctc',name:'СТС',url:'http://smarttv.ctc.ru',text:'Все самые интересные сериалы, популярные программы и мультфильмы телеканала СТС'},
  {appid:'siptv',name:'Smart IPTV',url:'http://opera.siptv.eu',text:'Play IPTV streams, videos on your Smart TV'},
  {appid:'ttktv',name:'ТТК ТВ',url:'http://eltex-web.ls.tv.ttk.ru',text:'Приложение для просмотра любимых фильмов, сериалов, мультфильмов и телевизионных программ'},
  {appid:'sibseti',name:'Тв Сибсети',url:'http://smarty.nsk.211.ru',text:'IPTV для абонентов Сибсети. Создай свой личный медиацентр с нашим приложением!'},

  {appid:'zefirtv',name:'Зефир ТВ',url:'http://webkit.zt.platform24.tv/',text:'ТВ-каналы, фильмы, сериалы, спорт'},
  {appid:'smotrim',name:'Смотрим',url:'https://tv.smotrim.ru/',text:'Новости, ток-шоу, документальные и художественные фильмы, телесериалы и пр.'},
  {appid:'moovi',name:'moovi',url:'http://base.portal.moovi-iptv.ru/ui/1280/index.html?rand=0.3412177627522204',text:'Кабельное Телевидение Moovi. Современный формат цифрового телевидения.'},
  {appid:'tvoe',name:'TVOE',url:'https://app.tvoe.live?device=smart-tv&installed=vidaa',text:'Тысячи фильмов и сериалов'},
  {appid:'emby',name:'Emby',url:'http://tv.emby.media/',text:'Медиа-сервер и домашний кинотеатр. Позволяет скачивать фильмы, сериалы и добавлять их в каталог.'},
  {appid:'24_1',name:'24tv',url:'http://webkit.24h.tv',text:'24ТВ — Всё ТВ и кинотеатры в одном приложении'},
  {appid:'IDC',name:'IDC Smart TV',url:'https://smart.iptv.idc.md',text:'Приложение от крупнейшего телекоммуникационного оператора на территории Приднестровья'},

  {appid:'stremio',name:'Stremio',url:'https://tv.strem.io',text:'Stremio – программа для просмотра видео-контента различных известных онлайн-сервисов'},
  {appid:'tytkino',name:'Тут Кино',url:'http://fork-p0rtal.ru/project/',text:'Виджет для SmartTV от fork-portal.ru на движке VPlay.'},
  {appid:'impareboom',name:'ИмперияBOOM',url:'http://web.imboom.ru/',text:'Твой HD кинотеатр. Новинки кино и сериалы без навязчивой рекламы'},
  {appid:'kb_msx',name:'KinoBoom',url:'http://msx.benzac.de/?start=content:http://kb-team.club/msx/enter.php',text:'Новинки кино и сериалы'},
  {appid:'djin',name:'HDGO',url:'http://hdgo.me/',text:'Полностью готовый к работе форк Lampa Lite'},
  {appid:'popkorn',name:'Попкорн',url:'https://tv-desktop.beepopcorn.ru',text:'Бесплатное ТВ, фильмы, сериалы, видеоблоги и караоке'},

  {appid:'filmix',name:'Filmix',url:'http://filmix.tv',text:'Приложение для просмотра фильмов и сериалов с популярного онлайн кинотеатра filmix.tv'},
  {appid:'akter',name:'AKTER BLACK',url:'http://abvidaa.ru',text:'Уютное киноубежище — онлайн кинотеатр AKTER BLACK'},
  {appid:'movix',name:'Movix',url:'http://cdn.smarttv.domru.ru/hisense/',text:'Устройте онлайн-кинотеатр у себя дома вместе с Movix!'},
  {appid:'jellyfin',name:'jellyfin',url:'https://jellyfin-vidaa.vercel.app',text:'Бесплатный и свободный медиасервер'},
  {appid:'farlinetv',name:'Фарлайн ТВ',url:'http://tv.farline.net',text:'Смотрите наше интерактивное телевидение онлайн в любое удобное для вас время! Фильмы, мультфильмы, шоу и новости.'},
  {appid:'sevstartv',name:'Севстар Тв',url:'http://tvs.sevstar.net',text:'Приложение для просмотра пакетов Цифрового телевидения от компании Севстар'},
  {appid:'focustv',name:'Фокус Лайф',url:'http://tv.focus.life/',text:'Приложение для просмотра пакетов Цифрового телевидения от компании Фокус Лайф'},
  {appid:'litehdtv',name:'Лайт HD TV',url:'https://hosted.litehd.tv/webos/',text:'Простое, удобное и лёгкое в использовании приложение. Более 200 ТВ-каналов бесплатно'},
  {appid:'limehdtv',name:'Лайм HD TV',url:'https://hosted.limehd.tv/webos/',text:'Бесплатные фильмы, новости, спорт, комедии и многое другое для вас в одном приложении'},
  {appid:'ufanet',name:'Уфанет',url:'http://webkit.ufanet.platform24.tv/',text:'Уфанет ТВ: сотни фильмов, сериалов и телеканалов в одном приложении'},
];
