var apps = [

{appid:'lampa',name:'Lampa',url:'http://lampa.mx/',text:'РќРѕРІРѕРµ РїРѕР»РЅРѕСЃС‚СЊСЋ Р±РµСЃРїР»Р°С‚РЅРѕРµ РїСЂРёР»РѕР¶РµРЅРёРµ РґР»СЏ Smart TV'},
{appid:'vokino',name:'vokino',url:'http://web.vokino.pro/',text:'РЎРјРѕС‚СЂРµС‚СЊ Р·Р°СЂСѓР±РµР¶РЅС‹Рµ С„РёР»СЊРјС‹ Рё СЃРµСЂРёР°Р»С‹ РІ С…РѕСЂРѕС€РµРј РєР°С‡РµСЃС‚РІРµ'},
{appid:'atodo',name:'Atodo',url:'http://msx.benzac.de/?start=menu:request:interaction:menu@http://atodo.fun/fun.html',text:'РђРўРћDO'},
{appid:'fxml',name:'Media Station X',url:'http://msx.benzac.de/foxxum.html',text:'РџСЂРёР»РѕР¶РµРЅРёРµ РґР»СЏ СЃРѕР·РґР°РЅРёСЏ РЅР°СЃС‚СЂР°РёРІР°РµРјС‹С… РјСѓР»СЊС‚РёРјРµРґРёР№РЅС‹С… СЃС‚СЂР°РЅРёС† (РІРёРґРµРѕ, Р°СѓРґРёРѕ Рё РїСЂ.)'},
{appid:'moovies',name:'Moovies',url:'http://msx.benzac.de/?start=menu:request:interaction:init@http://moovies.uz/index.html',text:'Moovies for MSX'},
{appid:'movielab',name:'Movielab',url:'https://msx.benzac.de/?start=menu:https://movielab.fun/msx/menu.json',text:'РќР°СЃР»Р°Р¶РґР°Р№С‚РµСЃСЊ РїСЂРѕСЃРјРѕС‚СЂРѕРј Р»СѓС‡С€РёС… С„РёР»СЊРјРѕРІ СЃ MovieLab'},
{appid:'deeplex',name:'DEEPLEX',url:'http://smart.deeplex.cc',text:'Р¤РёР»СЊРјС‹, СЃРµСЂРёР°Р»С‹ Рё РјРЅРѕРіРѕРµ РґСЂСѓРіРѕРµ Р±РµР· РѕРіСЂР°РЅРёС‡РµРЅРёР№.РРЅСЃС‚СЂСѓРєС†РёСЏ -> http://deeplex.cc/#/instructions'},
{appid:'drmplay',name:'DRM-play',url:'http://drm-play.com',text:'Ott РїР»РµРµСЂ drm-play, mod РїР»РµРµСЂР° ott-play by Alex '},
//{appid:'msx',name:'MSXPlayer',url:'http://msx.benzac.de/?welcome=menu:request:interaction:menu@http://plugins.msxplayer.ru/store.html',text:'Р›Р°СѓРЅС‡РµСЂ РїСЂРёР»РѕР¶РµРЅРёР№, TorrServer-РєР»РёРµРЅС‚, FXML-Р±СЂР°СѓР·РµСЂ, IPTV-РїСЂРѕСЃРјРѕС‚СЂвЂ¦'},
{appid:'fork',name:'ForkPlayer',url:'http://browser.appfxml.com/',text:'ForkPlayer вЂ” СЌС‚Рѕ Р±СЂР°СѓР·РµСЂ СЃ Р°РґР°РїС‚РёСЂРѕРІР°РЅРЅС‹Рј РїРѕРґ РІР°С€Рµ СѓСЃС‚СЂРѕР№СЃС‚РІРѕ РїСЂРѕСЃРјРѕС‚СЂРѕРј СЃР°Р№С‚РѕРІ'},
{appid:'forkbrowser',name:'Fork Browser',url:'http://browser.appinfo.su/',text:'РќРѕРІР°СЏ, СѓР»СѓС‡С€РµРЅРЅР°СЏ РІРµСЂСЃРёСЏ ForkPlayer'},
{appid:'lampalite4',name:'Lampa lite',url:'http://lite.lampa.mx/',text:'Lampa Lite, РѕР±Р»РµРіС‡РµРЅРЅР°СЏ РІРµСЂСЃРёСЏ РїСЂРёР»РѕР¶РµРЅРёСЏ РґР»СЏ РѕРЅР»Р°Р№РЅ РїСЂРѕСЃРјРѕС‚СЂР°.'},
{appid:'twitch',name:'twitch',url:'https://ryxjogfhxnvjuptmzkhk.tv.twitch.tv',text:'Р’РёРґРµРѕСЃС‚СЂРёРјРёРЅРіРѕРІС‹Р№ СЃРµСЂРІРёСЃ, СЃРїРµС†РёР°Р»РёР·РёСЂСѓСЋС‰РёР№СЃСЏ РЅР° С‚РµРјР°С‚РёРєРµ РєРѕРјРїСЊСЋС‚РµСЂРЅС‹С… РёРіСЂ.'},
{appid:'vkvideo',name:'VK РІРёРґРµРѕ',url:'https://vk.ru/tv-app/lib?version=latest&platform=vidaa',text:'РЎРјРѕС‚СЂРёС‚Рµ РІРёРґРµРѕР·Р°РїРёСЃРё Р’РљРѕРЅС‚Р°РєС‚Рµ РЅР° Р±РѕР»СЊС€РѕРј СЌРєСЂР°РЅРµ SmartTV. '},

{appid:'beeline',name:'Р‘РёР»Р°Р№РЅ РўР’',url:'https://smart-vidaa.beeline.tv/',text:'РўС‹СЃСЏС‡Рё С„РёР»СЊРјРѕРІ, СЃРµСЂРёР°Р»РѕРІ Рё РјСѓР»СЊС‚С„РёР»СЊРјРѕРІ. 300 РєР°РЅР°Р»РѕРІ Рё РґРѕСЃС‚СѓРї Рє РѕРЅР»Р°Р№РЅ-РєРёРЅРѕС‚РµР°С‚СЂСѓ beeline.tv.'},
{appid:'xsmart',name:'Xsmart',url:'http://app.xsmart.tv/?widg=5',text:'РџСЂРёР»РѕР¶РµРЅРёРµ РґР»СЏ Smart TV, РєРѕС‚РѕСЂРѕРµ РѕР±СЉРµРґРёРЅСЏРµС‚ РІ СЃРµР±Рµ СЂР°Р·Р»РёС‡РЅС‹Рµ С„СѓРЅРєС†РёРё.'},
//{appid:'xsmartlite',name:'Xsmart classic',url:'http://app.xsmart.tv/?widg=lite',text:'РџСЂРёР»РѕР¶РµРЅРёРµ РґР»СЏ Smart TV, РєРѕС‚РѕСЂРѕРµ РѕР±СЉРµРґРёРЅСЏРµС‚ РІ СЃРµР±Рµ СЂР°Р·Р»РёС‡РЅС‹Рµ С„СѓРЅРєС†РёРё. Lite РІРµСЂСЃРёСЏ РїСЂРёР»РѕР¶РµРЅРёСЏ.'},
{appid:'viju',name:'Viju',url:'https://smarttv.viju.ru',text:'Viju вЂ“ СЌС‚Рѕ Р»СѓС‡С€РёРµ С„РёР»СЊРјС‹, СЃРµСЂРёР°Р»С‹ Рё РјСѓР»СЊС‚С„РёР»СЊРјС‹ РїРѕ РїРѕРґРїРёСЃРєРµ'},
//{appid:'lava',name:'LAVA',url:'https://html5.lavaonline.tv',text:'РџР»РѕС‰Р°РґРєР° РґР»СЏ Р±РµСЃРїР»Р°С‚РЅРѕРіРѕ РїСЂРѕСЃРјРѕС‚СЂР° СЃРѕРІСЂРµРјРµРЅРЅРѕРіРѕ СЂРѕСЃСЃРёР№СЃРєРѕРіРѕ РєРёРЅРѕ'},
//{appid:'tiktok',name:'TikTok',url:'https://tv.tiktok.com/webos',text:'Р’РµРґСѓС‰Р°СЏ РІРёРґРµРѕРїР»Р°С‚С„РѕСЂРјР° РґР»СЏ РєРѕСЂРѕС‚РєРёС… РІРёРґРµРѕ'},
{appid:'flex',name:'FLEX',url:'https://tv.back-films.ru',text:'РћРЅР»Р°Р№РЅ-РєРёРЅРѕС‚РµР°С‚СЂ СЃ С„РёР»СЊРјР°РјРё Рё СЃРµСЂРёР°Р»Р°РјРё РІ РѕС‚Р»РёС‡РЅРѕРј РєР°С‡РµСЃС‚РІРµ Рё РїСЂРѕС„РµСЃСЃРёРѕРЅР°Р»СЊРЅРѕРј РѕР·РІСѓС‡РёРІР°РЅРёРё!'},
{appid:'m3uiptv',name:'M3U IPTV',url:'https://m3u-ip.tv/lg/',text:'РџСЂРѕСЃС‚Рѕ Р·Р°РіСЂСѓР·РёС‚Рµ СЃРІРѕР№ РїР»РµР№Р»РёСЃС‚ IPTV РїРѕ URL-Р°РґСЂРµСЃСѓ (РІ РІРёРґРµ С„Р°Р№Р»Р° m3u РёР»Рё m3u8) Рё РІРїРµСЂРµРґ'},
{appid:'kinopoisk',name:'РљРёРЅРѕРїРѕРёСЃРє',url:'https://smarttv-app.ott.yandex.ru/?ott-rv=vidaa',text:'РљСЂСѓРїРЅРµР№С€РёР№ СЂСѓСЃСЃРєРѕСЏР·С‹С‡РЅС‹Р№ РѕРЅР»Р°Р№РЅ-РєРёРЅРѕС‚РµР°С‚СЂ.'},
{appid:'yandexvideo',name:'РЇРЅРґРµРєСЃ РІРёРґРµРѕ',url:'https://yandex.ru/video/tvapp/?ui=tvapp',text:'CРјРѕС‚СЂРµС‚СЊ С‚РµР»РµРїРµСЂРµРґР°С‡Рё, РјСѓР·С‹РєР°Р»СЊРЅС‹Рµ РєР»РёРїС‹, РёРіСЂРѕРІС‹Рµ СЂРѕР»РёРєРё Рё РїРѕРїСѓР»СЏСЂРЅРѕРµ РЅР° YouTube'},
{appid:'ott',name:'OttPlayer',url:'http://widget.ottplayer.tv/operatv2/index.html',text:'CРµСЂРІРёСЃ, РєРѕС‚РѕСЂС‹Р№ РїРѕР·РІРѕР»СЏРµС‚ РІР°Рј СЃРѕР±СЂР°С‚СЊ РІСЃС‘ РІР°С€Рµ IP-С‚РµР»РµРІРёРґРµРЅРёРµ РІ РѕРґРЅРѕРј РїР»РµР№Р»РёСЃС‚Рµ.'},
{appid:'ottold',name:'OttPlayerTest',url:'http://widget.ottplayer.tv/test/index.html',text:'OttPlayer, Р±РѕР»РµРµ РЅРѕРІР°СЏ(С‚РµСЃС‚РѕРІР°СЏ РІРµСЂСЃРёСЏ РїСЂРёР»РѕР¶РµРЅРёСЏ)'},
{appid:'wink',name:'Wink',url:'https://production-vidaa-fhd.wink.ru/',text:'Р¦РёС„СЂРѕРІРѕР№ РІРёРґРµРѕСЃРµСЂРІРёСЃ РєРѕРјРїР°РЅРёРё В«Р РѕСЃС‚РµР»РµРєРѕРјВ»'},
{appid:'kion',name:'РљРёРѕРЅ',url:'http://hkion.kion.ru/',text:'Р РѕСЃСЃРёР№СЃРєР°СЏ РјСѓР»СЊС‚РёРјРµРґРёР№РЅР°СЏ РѕРЅР»Р°Р№РЅ-РїР»Р°С‚С„РѕСЂРјР°, СЃРѕР·РґР°РЅРЅР°СЏ РєРѕРјРїР°РЅРёРµР№ РњРўРЎ'},
{appid:'ssiptv',name:'ssiptv',url:'http://app.ss-iptv.com',text:'РњРµРґРёР° СЃРµСЂРІРµСЂ РґР»СЏ РїСЂРѕСЃРјРѕС‚СЂР° С„РёР»СЊРјРѕРІ, СЃРµСЂРёР°Р»РѕРІ, РјСѓР»СЊС‚С„РёР»СЊРјРѕРІ Рё РїСЂ.'},
{appid:'icva',name:'ICVA',url:'http://icva.mx/',text:'ICVA - РЅРѕРІРѕРµ РїСЂРёР»РѕР¶РµРЅРёРµ РґР»СЏ РїСЂРѕСЃРјРѕС‚СЂР° IPTV РєР°РЅР°Р»РѕРІ'},

{appid:'tvap',name:'TVap',url:'http://tvphone.site/',text:'TVap - РїСЂРѕСЃРјРѕС‚СЂ IPTV РєР°РЅР°Р»РѕРІ РЅР° Smart TV'},
{appid:'peers',name:'PeersTV',url:'http://smarttv.peers.tv/hisense/hisense-1.0.0/',text:'Р‘РµСЃРїР»Р°С‚РЅРѕРµ РїСЂРёР»РѕР¶РµРЅРёРµ РґР»СЏ РїСЂРѕСЃРјРѕС‚СЂР° РўР’ РѕРЅР»Р°Р№РЅ Рё РІ Р·Р°РїРёСЃРё. Р›Р°Р№С‚ РІРµСЂСЃРёСЏ Р±РµР· СЂРµРєР»Р°РјС‹'},
{appid:'bonus',name:'Р‘РѕРЅСѓСЃ РўР’',url:'http://app.bonus-tv.ru/lg/',text:'РўРµР»РµРІРёРґРµРЅРёРµ РѕРЅР»Р°Р№РЅ РЅР° СЃРјР°СЂС‚С„РѕРЅРµ, РїР»Р°РЅС€РµС‚Рµ, Smart-С‚РµР»РµРІРёР·РѕСЂРµ РёР»Рё РўР’-РїСЂРёСЃС‚Р°РІРєРµ.'},
{appid:'amediateka',name:'AРјРµРґРёР°С‚РµРєР°',url:'https://smarttv.amediateka.tech/v2/vidaa/',text:'РћРЅР»Р°Р№РЅ-СЃРµСЂРІРёСЃ РђРјРµРґРёР°С‚РµРєР° Рё С‚РµР»РµРєР°РЅР°Р»С‹ AMEDIA TV. Р›СѓС‡С€РёРµ СЃРµСЂРёР°Р»С‹ РїР»Р°РЅРµС‚С‹'},
//{appid:'forkbrowser',name:'Fork Browser',url:'http://browser.appinfo.su/',text:'РќРѕРІР°СЏ, СѓР»СѓС‡С€РµРЅРЅР°СЏ РІРµСЂСЃРёСЏ ForkPlayer'},
{appid:'prisma',name:'Prisma',url:'http://prisma.ws/',text:'РџРѕР»РЅРѕСЃС‚СЊСЋ РіРѕС‚РѕРІС‹Р№ Рє СЂР°Р±РѕС‚Рµ С„РѕСЂРє Lampa.'},
//{appid:'ott',name:'OttPlayer',url:'http://widget.ottplayer.tv/operatv2/index.html',text:'CРµСЂРІРёСЃ, РєРѕС‚РѕСЂС‹Р№ РїРѕР·РІРѕР»СЏРµС‚ РІР°Рј СЃРѕР±СЂР°С‚СЊ РІСЃС‘ РІР°С€Рµ IP-С‚РµР»РµРІРёРґРµРЅРёРµ РІ РѕРґРЅРѕРј РїР»РµР№Р»РёСЃС‚Рµ.'},
//{appid:'ottold',name:'OttPlayerTest',url:'http://widget.ottplayer.tv/test/index.html',text:'OttPlayer, Р±РѕР»РµРµ РЅРѕРІР°СЏ(С‚РµСЃС‚РѕРІР°СЏ РІРµСЂСЃРёСЏ РїСЂРёР»РѕР¶РµРЅРёСЏ)'},
{appid:'gets',name:'GetsTV',url:'https://getstv.com/app/',text:'РџСЂРёР»РѕР¶РµРЅРёРµ РґР»СЏ РїСЂРѕСЃРјРѕС‚СЂР° РўР’, С„РёР»СЊРјРѕРІ Рё СЃРµСЂРёР°Р»РѕРІ.'},
{appid:'ottplay_mod',name:'OTT-Play FOSS',url:'http://ott.prog4food.eu.org/f/',text:' MoРґ iptv РїР»РµРµСЂР° Ott-Play by Alex. РћС‚СЃСѓС‚СЃС‚РІРёРµ Р±Р°РЅРЅРµСЂРѕРІ Рё Р±Р»РѕРєРёСЂРѕРІРєРё РєР°РЅР°Р»РѕРІ.'},
{appid:'kinopub',name:'KinoPubTV',url:'http://cdnservices.link',text:'РќРµРѕС„РёС†РёР°Р»СЊРЅС‹Р№ РєР»РёРµРЅС‚ РґР»СЏ РїРѕРїСѓР»СЏСЂРЅРѕРіРѕ РѕРЅР»Р°Р№РЅ-РєРёРЅРѕС‚РµР°С‚СЂР°'},
//{appid:'kinopub2',name:'KinoPubTV',url:'https://kpms.cc',text:'РќРµРѕС„РёС†РёР°Р»СЊРЅС‹Р№ РєР»РёРµРЅС‚ РґР»СЏ РїРѕРїСѓР»СЏСЂРЅРѕРіРѕ РѕРЅР»Р°Р№РЅ-РєРёРЅРѕС‚РµР°С‚СЂР°.'},
//{appid:'kinopub2',name:'KinoPub',url:'http://kpstv.net/app/hisense/',text:'Р•С‰Рµ РѕРґРёРЅ РЅРµРѕС„РёС†РёР°Р»СЊРЅС‹Р№ РєР»РёРµРЅС‚ РґР»СЏ РѕРЅР»Р°Р№РЅ-РєРёРЅРѕС‚РµР°С‚СЂР° kinopub'},
{appid:'lampaun',name:'ByLampa',url:'http://bylampa.online/',text:'РќРµРѕС„РёС†РёР°Р»СЊРЅС‹Р№ С„РѕСЂРє РѕРЅР»Р°Р№РЅ-РєРёРЅРѕС‚РµР°С‚СЂР° Lampa'},
{appid:'lampaland',name:'Lampa.land',url:'http://lampa.land',text:'РџСЂРѕРµРєС‚, СЃРѕР·РґР°РЅРЅС‹Р№ РґР»СЏ С‚РµС…, РєС‚Рѕ РЅРµ РјРѕР¶РµС‚ СЃР°РјРѕСЃС‚РѕСЏС‚РµР»СЊРЅРѕ РЅР°СЃС‚СЂРѕРёС‚СЊ РїСЂРёР»РѕР¶РµРЅРёРµ Lampa'},
{appid:'iptvportal',name:'IPTVPORTAL',url:'http://go.iptvportal.ru/?screen=1280x720&user-agent=lg',text:'РџСЂРѕСЃРјРѕС‚СЂ IPTV РёР· СЃРµС‚РµР№ РїСЂРѕРІР°Р№РґРµСЂРѕРІ, РїРѕРґРєР»СЋС‡РµРЅРЅС‹С… Рє РїР»Р°С‚С„РѕСЂРјРµ IPTVPORTAL'},
{appid:'oneplayer',name:'Oneplayer',url:'http://webos.oneplayer.me/',text:'РРЅС‚РµСЂРЅРµС‚-РїР»РµРµСЂ СЃ С€РёСЂРѕРєРёРј С„СѓРЅРєС†РёРѕРЅР°Р»РѕРј'},
{appid:'clouddy',name:'ClouDDy',url:'http://player.clouddy.online/',text:'РџСЂРѕРґРІРёРЅСѓС‚С‹Р№ Рё СѓРґРѕР±РЅС‹Р№ РјРµРґРёР°РїР»РµРµСЂ РґР»СЏ РІРѕСЃРїСЂРѕРёР·РІРµРґРµРЅРёСЏ РІР°С€РµРіРѕ Р»СЋР±РёРјРѕРіРѕ РјРµРґРёР°РєРѕРЅС‚РµРЅС‚Р°.'},

{appid:'smotreshka',name:'РЎРјРѕС‚СЂРµС€РєР°',url:'https://smotreshka.webapp.lfstrm.tv/loaders/vidaa/index.html',text:'РЎРѕРІСЂРµРјРµРЅРЅРѕРµ РёРЅС‚РµСЂР°РєС‚РёРІРЅРѕРµ С‚РµР»РµРІРёРґРµРЅРёРµ'},
//{appid:'ivikids',name:'IVI РґРµС‚СЏРј',url:'http://lgkids.ivi.ru',text:'РџСЂРёР»РѕР¶РµРЅРёРµ, СЃРґРµР»Р°РЅРЅРѕРµ СЃРїРµС†РёР°Р»СЊРЅРѕ РґР»СЏ РґРµС‚РµР№! РњСѓР»СЊС‚РёРєРё, С„РёР»СЊРјС‹ Рё СЃРµСЂРёР°Р»С‹'},
{appid:'viloud',name:'Viloud',url:'https://app.viloud.tv//smarttv//v2//?associate=fox-a5f1&app=ef2b1dd758eb0fcc065561e1275e4af6#viloud',text:'РЎР°РјР°СЏ РџСЂРѕСЃС‚Р°СЏ Рё Р”РѕСЃС‚СѓРїРЅР°СЏ РћРЅР»Р°Р№РЅ-Р’РёРґРµРѕРїР»Р°С‚С„РѕСЂРјР°'},
{appid:'vevo',name:'Vevo',url:'https://hisense.vevo.com',text:'РњСѓР·С‹РєР°Р»СЊРЅРѕРµ РІРёРґРµРѕ РѕС‚ РєСЂСѓРїРЅРµР№С€РёС… Р·РІСѓРєРѕР·Р°РїРёСЃС‹РІР°СЋС‰РёС… РєРѕСЂРїРѕСЂР°С†РёР№'},
{appid:'webvideocast2',name:'Web Video Cast',url:'http://vewd.webvideocaster.com/',text:'РџРѕР·РІРѕР»СЏРµС‚ РІР°Рј С‚СЂР°РЅСЃР»РёСЂРѕРІР°С‚СЊ Р»СЋР±РѕРµ РІРёРґРµРѕ, РЅР°Р№РґРµРЅРЅРѕРµ РЅР° РІРµР±-СЃР°Р№С‚Р°С…, РЅР° РІР°С€ С‚РµР»РµРІРёР·РѕСЂ.'},
{appid:'sweet',name:'sweet.tv',url:'http://foxxum240.sweet.tv',text:'Р‘РµСЃРїР»Р°С‚РЅРѕРµ РѕРЅР»Р°Р№РЅ С‚РµР»РµРІРёРґРµРЅРёРµ РІ С…РѕСЂРѕС€РµРј РєР°С‡РµСЃС‚РІРµ. РўРµР»РµРєР°РЅР°Р»С‹ РІ РїСЂСЏРјРѕРј СЌС„РёСЂРµ Рё РІ Р·Р°РїРёСЃРё!'},
{appid:'stranafm',name:'РЎС‚СЂР°РЅР° FM',url:'http://stranafm.bonus-tv.ru/stranafm/nettv/',text:'РЎС‚СЂР°РЅР° FM вЂ” СЂРѕСЃСЃРёР№СЃРєРёР№ РєРѕРјРјРµСЂС‡РµСЃРєРёР№ СЂР°Р·РІР»РµРєР°С‚РµР»СЊРЅС‹Р№ С‚РµР»РµРєР°РЅР°Р». РњСѓР·С‹РєР° РЅРѕРЅ СЃС‚РѕРї'},
{appid:'premier',name:'PREMIER',url:'https://hisensesmarttv.premier.one/hisense/#/main',text:'РўРќРў РїСЂРµРјСЊРµСЂ. РќРѕРІС‹Рµ СЂСѓСЃСЃРєРёРµ СЃРµСЂРёР°Р»С‹, С„РёР»СЊРјС‹ Рё С€РѕСѓ.'},
{appid:'mytuner',name:'myTuner Radio',url:'https://devices.mytuner.mobi/?utm_source=Foxxum',text:'РЈРґРѕР±РЅРѕРµ РїСЂРѕСЃР»СѓС€РёРІР°РЅРёРµ Р±РѕР»РµРµ 30 000 РїРѕРїСѓР»СЏСЂРЅС‹С… СЂР°РґРёРѕСЃС‚Р°РЅС†РёР№ 120 СЃС‚СЂР°РЅ РјРёСЂР°'},
{appid:'zaycev',name:'Zaycev FM',url:'https://tv.zaycev.fm/index.html',text:'Р›СЋР±РёРјР°СЏ РјСѓР·С‹РєР° С‚РµРїРµСЂСЊ РІСЃРµРіРґР° Р±СѓРґРµС‚ СЃ РІР°РјРё РІРјРµСЃС‚Рµ СЃ РѕРЅР»Р°Р№РЅ СЂР°РґРёРѕ Zaycev.fm!'},
{appid:'ctc',name:'РЎРўРЎ',url:'http://smarttv.ctc.ru',text:'Р’СЃРµ СЃР°РјС‹Рµ РёРЅС‚РµСЂРµСЃРЅС‹Рµ СЃРµСЂРёР°Р»С‹, РїРѕРїСѓР»СЏСЂРЅС‹Рµ РїСЂРѕРіСЂР°РјРјС‹ Рё РјСѓР»СЊС‚С„РёР»СЊРјС‹ С‚РµР»РµРєР°РЅР°Р»Р° РЎРўРЎ'},
{appid:'siptv',name:'Smart IPTV',url:'http://opera.siptv.eu',text:'Play IPTV streams, videos on your Smart TV'},
{appid:'ttktv',name:'РўРўРљ РўР’',url:'http://eltex-web.ls.tv.ttk.ru',text:'РџСЂРёР»РѕР¶РµРЅРёРµ РґР»СЏ РїСЂРѕСЃРјРѕС‚СЂР° Р»СЋР±РёРјС‹С… С„РёР»СЊРјРѕРІ, СЃРµСЂРёР°Р»РѕРІ, РјСѓР»СЊС‚С„РёР»СЊРјРѕРІ Рё С‚РµР»РµРІРёР·РёРѕРЅРЅС‹С… РїСЂРѕРіСЂР°РјРј'},
{appid:'sibseti',name:'TРІ РЎРёР±СЃРµС‚Рё',url:'http://smarty.nsk.211.ru',text:'IPTV РґР»СЏ Р°Р±РѕРЅРµРЅС‚РѕРІ РЎРёР±СЃРµС‚Рё. РЎРѕР·РґР°Р№ СЃРІРѕР№ Р»РёС‡РЅС‹Р№ РјРµРґРёР°С†РµРЅС‚СЂ СЃ РЅР°С€РёРј РїСЂРёР»РѕР¶РµРЅРёРµРј!'},

{appid:'zefirtv',name:'Р—РµС„РёСЂ РўР’',url:'http://webkit.zt.platform24.tv/',text:'РўР’-РєР°РЅР°Р»С‹, С„РёР»СЊРјС‹, СЃРµСЂРёР°Р»С‹, СЃРїРѕСЂС‚'},
{appid:'smotrim',name:'РЎРјРѕС‚СЂРёРј',url:'https://tv.smotrim.ru/',text:'РќРѕРІРѕСЃС‚Рё, С‚РѕРє-С€РѕСѓ, РґРѕРєСѓРјРµРЅС‚Р°Р»СЊРЅС‹Рµ Рё С…СѓРґРѕР¶РµСЃС‚РІРµРЅРЅС‹Рµ С„РёР»СЊРјС‹, С‚РµР»РµСЃРµСЂРёР°Р»С‹ Рё РїСЂ.'},
{appid:'moovi',name:'moovi',url:'http://base.portal.moovi-iptv.ru/ui/1280/index.html?rand=0.3412177627522204',text:'РљР°Р±РµР»СЊРЅРѕРµ РўРµР»РµРІРёРґРµРЅРёРµ Moovi. РЎРѕРІСЂРµРјРµРЅРЅС‹Р№ С„РѕСЂРјР°С‚ С†РёС„СЂРѕРІРѕРіРѕ С‚РµР»РµРІРёРґРµРЅРёСЏ.'},
{appid:'tvoe',name:'TVOE',url:'https://app.tvoe.live?device=smart-tv&installed=vidaa',text:'РўС‹СЃСЏС‡Рё С„РёР»СЊРјРѕРІ Рё СЃРµСЂРёР°Р»РѕРІ'},
{appid:'emby',name:'Emby',url:'http://tv.emby.media/',text:'РњРµРґРёР°-СЃРµСЂРІРµСЂ Рё РґРѕРјР°С€РЅРёР№ РєРёРЅРѕС‚РµР°С‚СЂ. РџРѕР·РІРѕР»СЏРµС‚ СЃРєР°С‡РёРІР°С‚СЊ С„РёР»СЊРјС‹, СЃРµСЂРёР°Р»С‹ Рё РґРѕР±Р°РІР»СЏС‚СЊ РёС… РІ РєР°С‚Р°Р»РѕРі.'},
{appid:'24_1',name:'24tv',url:'http://webkit.24h.tv',text:'24РўР’ Р’СЃС‘ РўР’ Рё РєРёРЅРѕС‚РµР°С‚СЂС‹ РІ РѕРґРЅРѕРј РїСЂРёР»РѕР¶РµРЅРёРё'},
{appid:'IDC',name:'IDC Smart TV',url:'https://smart.iptv.idc.md',text:'РџСЂРёР»РѕР¶РµРЅРёРµ РѕС‚ РєСЂСѓРїРЅРµР№С€РµРіРѕ С‚РµР»РµРєРѕРјРјСѓРЅРёРєР°С†РёРѕРЅРЅРѕРіРѕ РѕРїРµСЂР°С‚РѕСЂР° РЅР° С‚РµСЂСЂРёС‚РѕСЂРёРё РџСЂРёРґРЅРµСЃС‚СЂРѕРІСЊСЏ'},

{appid:'stremio',name:'Stremio',url:'https://tv.strem.io',text:'Stremio вЂ“ РїСЂРѕРіСЂР°РјРјР° РґР»СЏ РїСЂРѕСЃРјРѕС‚СЂР° РІРёРґРµРѕ-РєРѕРЅС‚РµРЅС‚Р° СЂР°Р·Р»РёС‡РЅС‹С… РёР·РІРµСЃС‚РЅС‹С… РѕРЅР»Р°Р№РЅ-СЃРµСЂРІРёСЃРѕРІ'},
{appid:'tytkino',name:'РўСѓС‚ РљРёРЅРѕ',url:'http://fork-p0rtal.ru/project/',text:'Р’РёРґР¶РµС‚ РґР»СЏ SmartTV РѕС‚ fork-portal.ru РЅР° РґРІРёР¶РєРµ VPlay.'},
{appid:'impareboom',name:'РРјРїРµСЂРёСЏBOOM',url:'http://web.imboom.ru/',text:'РўРІРѕР№ HD РєРёРЅРѕС‚РµР°С‚СЂ. РќРѕРІРёРЅРєРё РєРёРЅРѕ Рё СЃРµСЂРёР°Р»С‹ Р±РµР· РЅР°РІСЏР·С‡РёРІРѕР№ СЂРµРєР»Р°РјС‹'},
{appid:'kb_msx',name:'KinoBoom',url:'http://msx.benzac.de/?start=content:http://kb-team.club/msx/enter.php',text:'РќРѕРІРёРЅРєРё РєРёРЅРѕ Рё СЃРµСЂРёР°Р»С‹'},
{appid:'djin',name:'HDGO',url:'http://hdgo.me/',text:'РџРѕР»РЅРѕСЃС‚СЊСЋ РіРѕС‚РѕРІС‹Р№ Рє СЂР°Р±РѕС‚Рµ С„РѕСЂРє Lampa Lite'},
{appid:'popkorn',name:'РџРѕРїРєРѕСЂРЅ',url:'https://tv-desktop.beepopcorn.ru',text:'Р‘РµСЃРїР»Р°С‚РЅРѕРµ РўР’, С„РёР»СЊРјС‹, СЃРµСЂРёР°Р»С‹, РІРёРґРµРѕР±Р»РѕРіРё Рё РєР°СЂР°РѕРєРµ'},

{appid:'filmix',name:'Filmix',url:'http://filmix.tv',text:'РџСЂРёР»РѕР¶РµРЅРёРµ РґР»СЏ РїСЂРѕСЃРјРѕС‚СЂР° С„РёР»СЊРјРѕРІ Рё СЃРµСЂРёР°Р»РѕРІ СЃ РїРѕРїСѓР»СЏСЂРЅРѕРіРѕ РѕРЅР»Р°Р№РЅ РєРёРЅРѕС‚РµР°С‚СЂР° filmix.tv'},
{appid:'akter',name:'AKTER BLACK',url:'http://abvidaa.ru',text:'РЈСЋС‚РЅРѕРµ РєРёРЅРѕСѓР±РµР¶РёС‰Рµ - РѕРЅР»Р°Р№РЅ РєРёРЅРѕС‚РµР°С‚СЂ AKTER BLACK'},
{appid:'movix',name:'Movix',url:'http://cdn.smarttv.domru.ru/hisense/',text:'РЈСЃС‚СЂРѕР№С‚Рµ РѕРЅР»Р°Р№РЅ-РєРёРЅРѕС‚РµР°С‚СЂ Сѓ СЃРµР±СЏ РґРѕРјР° РІРјРµСЃС‚Рµ СЃ Movix!'},
{appid:'jellyfin',name:'jellyfin',url:'https://jellyfin-vidaa.vercel.app',text:'Р‘РµСЃРїР»Р°С‚РЅС‹Р№ Рё СЃРІРѕР±РѕРґРЅС‹Р№ РјРµРґРёР°СЃРµСЂРІРµСЂ'},
{appid:'farlinetv',name:'Р¤Р°СЂР»Р°Р№РЅ РўР’',url:'http://tv.farline.net',text:'РЎРјРѕС‚СЂРёС‚Рµ РЅР°С€Рµ РёРЅС‚РµСЂР°РєС‚РёРІРЅРѕРµ С‚РµР»РµРІРёРґРµРЅРёРµ РѕРЅР»Р°Р№РЅ РІ Р»СЋР±РѕРµ СѓРґРѕР±РЅРѕРµ РґР»СЏ РІР°СЃ РІСЂРµРјСЏ! Р¤РёР»СЊРјС‹, РјСѓР»СЊС‚С„РёР»СЊРјС‹, С€РѕСѓ Рё РЅРѕРІРѕСЃС‚Рё.'},
{appid:'sevstartv',name:'РЎРµРІСЃС‚Р°СЂ TРІ',url:'http://tvs.sevstar.net',text:'РџСЂРёР»РѕР¶РµРЅРёРµ РґР»СЏ РїСЂРѕСЃРјРѕС‚СЂР° РїР°РєРµС‚РѕРІ Р¦РёС„СЂРѕРІРѕРіРѕ С‚РµР»РµРІРёРґРµРЅРёСЏ РѕС‚ РєРѕРјРїР°РЅРёРё РЎРµРІСЃС‚Р°СЂ'},
{appid:'focustv',name:'Р¤РѕРєСѓСЃ Р›Р°Р№С„',url:'http://tv.focus.life/',text:'РџСЂРёР»РѕР¶РµРЅРёРµ РґР»СЏ РїСЂРѕСЃРјРѕС‚СЂР° РїР°РєРµС‚РѕРІ Р¦РёС„СЂРѕРІРѕРіРѕ С‚РµР»РµРІРёРґРµРЅРёСЏ РѕС‚ РєРѕРјРїР°РЅРёРё Р¤РѕРєСѓСЃ Р›Р°Р№С„'},
{appid:'litehdtv',name:'Р›Р°Р№С‚ HD TV',url:'https://hosted.litehd.tv/webos/',text:'РџСЂРѕСЃС‚РѕРµ, СѓРґРѕР±РЅРѕРµ Рё Р»РµРіРєРѕРµ РІ РёСЃРїРѕР»СЊР·РѕРІР°РЅРёРё РїСЂРёР»РѕР¶РµРЅРёРµ. Р‘РѕР»РµРµ 200 РўР’-РєР°РЅР°Р»РѕРІ Р±РµСЃРїР»Р°С‚РЅРѕ'},
{appid:'limehdtv',name:'Р›Р°Р№Рј HD TV',url:'https://hosted.limehd.tv/webos/',text:'Р‘РµСЃРїР»Р°С‚РЅС‹Рµ С„РёР»СЊРјС‹, РЅРѕРІРѕСЃС‚Рё, СЃРїРѕСЂС‚, РєРѕРјРµРґРёРё Рё РјРЅРѕРіРѕРµ РґСЂСѓРіРѕРµ РґР»СЏ РІР°СЃ РІ РѕРґРЅРѕРј РїСЂРёР»РѕР¶РµРЅРёРё'},
{appid:'ufanet',name:'РЈС„Р°РЅРµС‚',url:'http://webkit.ufanet.platform24.tv/',text:'РЈС„Р°РЅРµС‚ РўР’: СЃРѕС‚РЅРё С„РёР»СЊРјРѕРІ, СЃРµСЂРёР°Р»РѕРІ Рё С‚РµР»РµРєР°РЅР°Р»РѕРІ РІ РѕРґРЅРѕРј РїСЂРёР»РѕР¶РµРЅРёРё'},
];
